name: Test django-admin-sortable2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        Django-version: ["4.0"]
        node-version: ["16.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        npm ci --also=dev
        npx playwright install --with-deps
        python -m pip install --upgrade pip
        python -m pip install "Django==${{ matrix.Django-version }}.*"
        python -m pip install -r testapp/requirements.txt
        python -m playwright install
        python -m playwright install-deps
    - name: Build Client
      run: |
        npm run build
        npm run uglify
    - name: Test with pytest
      run: |
        python -m pytest testapp
